"""Brillouin-zone meshes and the primitive k-points a supercell run resolves.

Why this exists
---------------

Two of the package's diagnostics -- the unfolded density of states
(:mod:`unfoldlab.core.dos`) and the Fermi level (:mod:`unfoldlab.core.fermi`) --
integrate over the Brillouin zone and therefore need a *mesh* of supercell
k-points rather than a band path.  The user then asks the question this module
answers: **given a supercell run on a k-mesh, which primitive k-points can I
unfold onto, and is the one I want among them?**

A *generalized regular mesh* is generated by an integer matrix ``M`` and a
fractional shift ``s``: the k-points ``k`` with ``M k = m + s`` for an integer
vector ``m``, i.e. ``k = M^-1 (m + s)``.  The Gamma-centred Monkhorst--Pack mesh
with divisions ``(n1, n2, n3)`` is ``M = diag(n)`` and ``s = 0``; the usual
half-shifted mesh is the same ``M`` with ``s = (1/2, 1/2, 1/2)``, which is also
the convention in which VASP writes its ``KPOINTS`` shift, namely in units of
one mesh spacing.

The mathematics is settled in ``RequestProject/Unfolding/Mesh.lean``:

*a mesh is a fiber*
    ``UnfoldLab.Mesh_eq_setOf_foldsTo``: the mesh generated by ``M`` with shift
    ``s`` is the set of k-points that ``M`` folds onto ``s``.  Every fiber
    theorem therefore applies, in particular that the mesh has ``|det M|``
    points and that the same Smith-normal-form enumeration produces them
    (:func:`unfoldlab.core.lattice_quotient.coset_representatives`);

*the unfolded mesh is the mesh of the product*
    ``UnfoldLab.unfoldedMesh_eq``: the primitive k-points folding onto some
    point of the supercell mesh ``M`` are exactly the points of the mesh
    ``M @ T``, with the *same* shift.  So there are ``|det M| * |det T|`` of
    them, one full fiber above each supercell k-point
    (``UnfoldLab.IsFiberRepr.mesh_fiber_complete``), which is the situation in
    which the weight sum rules are equalities rather than bounds;

*the shift is not scaled by the folding*
    ``UnfoldLab.zero_mem_Mesh_iff``: Gamma is on a mesh exactly when the shift
    is integral.  A half-shifted supercell mesh resolves no primitive k-point
    of the corresponding Gamma-centred mesh -- Gamma itself included -- for any
    transform whatsoever;

*an odd mesh never sees the zone boundary*
    ``UnfoldLab.zoneBoundary_mem_iff``: the point ``1/2 e_i`` is sampled exactly
    when the division along ``i`` is even;

*the unfolded mesh is generally not a Monkhorst--Pack mesh*
    ``UnfoldLab.exists_unfoldedMesh_not_product``: for a non-unimodular ``T``
    the generator ``M @ T`` is not diagonal and the point set is not a product
    of one-dimensional meshes, so no triple of divisions describes it.
    :func:`diagnose_mesh` reports this as ``is_product_mesh``; the k-points have
    to be enumerated, which is what :func:`unfolded_mesh_points` does;

*and a mesh has a resolution*
    ``UnfoldLab.mesh_resolution_bound``: a k-point at half the mesh spacing is
    that far from every mesh point.  :func:`mesh_distance` measures the error of
    substituting the nearest resolvable k-point for a requested one, using the
    certified minimum-image search of :mod:`unfoldlab.core.valleys` so that the
    number is a Cartesian distance and not a fractional one.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product
from math import gcd
from typing import Any

import numpy as np
from numpy.typing import ArrayLike, NDArray

from unfoldlab.core.kpoints import KPoint, KPointMapping, fold_kpoint_to_supercell
from unfoldlab.core.lattice_quotient import coset_representatives
from unfoldlab.core.numerics import (
    TransformLike,
    as_array3,
    as_int_array,
    as_matrix3,
    check_atol,
    integer_adjugate3,
    integer_det3,
    wrap_fractional,
)
from unfoldlab.core.transformations import TransformationMatrix
from unfoldlab.core.valleys import minimum_image_distance

__all__ = [
    "MeshReport",
    "MeshSpec",
    "diagnose_mesh",
    "mesh_distance",
    "mesh_kpoint_mappings",
    "nearest_mesh_point",
    "unfolded_mesh",
    "unfolded_mesh_points",
]


def _transform_matrix(transform: TransformLike | TransformationMatrix) -> NDArray[np.int64]:
    if isinstance(transform, TransformationMatrix):
        return as_int_array(transform.matrix, name="transform")
    return as_int_array(as_matrix3(transform, name="transform"), name="transform")


@dataclass(frozen=True)
class MeshSpec:
    """A generalized regular k-mesh ``{k : M k = m + s, m integer}``.

    ``generator`` is the integer matrix ``M`` and ``shift`` the fractional
    offset ``s``, measured in units of one mesh spacing so that
    ``shift = (1/2, 1/2, 1/2)`` is the usual half-shifted mesh whatever the
    divisions are.  The mesh has ``|det M|`` points.
    """

    generator: NDArray[np.int64]
    shift: NDArray[np.float64]

    def __post_init__(self) -> None:
        matrix = as_int_array(as_matrix3(self.generator, name="generator"), name="generator")
        object.__setattr__(self, "generator", matrix)
        object.__setattr__(self, "shift", as_array3(self.shift, name="shift"))
        if self.determinant == 0:
            raise ValueError("mesh generator must be invertible (det != 0)")

    @classmethod
    def from_divisions(cls, divisions: ArrayLike, shift: ArrayLike | None = None) -> MeshSpec:
        """The Monkhorst--Pack mesh with the given divisions along each axis.

        ``shift`` is in units of one mesh spacing: ``(0.5, 0.5, 0.5)`` is the
        half-shifted mesh, and ``None`` means Gamma-centred.
        """

        counts = np.asarray(divisions, dtype=np.int64).reshape(-1)
        if counts.shape != (3,):
            raise ValueError(f"divisions must have shape (3,), got {counts.shape}")
        if np.any(counts <= 0):
            raise ValueError("divisions must be positive")
        offset = np.zeros(3, dtype=float) if shift is None else as_array3(shift, name="shift")
        return cls(generator=np.diag(counts), shift=offset)

    @property
    def determinant(self) -> int:
        """Exact ``det M``."""

        return integer_det3(self.generator)

    @property
    def count(self) -> int:
        """Number of distinct k-points, ``|det M|``."""

        return abs(self.determinant)

    @property
    def is_gamma_centred(self) -> bool:
        """Whether the shift is integral, which is when Gamma is a mesh point.

        ``UnfoldLab.zero_mem_Mesh_iff``.
        """

        return bool(np.all(np.abs(self.shift - np.rint(self.shift)) <= 1e-9))

    def points(self) -> NDArray[np.float64]:
        """The ``|det M|`` mesh points, wrapped into ``[0, 1)`` and sorted.

        The representatives ``m`` come from the Smith normal form of ``M``, and
        ``k = adj(M) (m + s) / det M`` uses the exact integer adjugate rather
        than a floating-point inverse.
        """

        offsets = coset_representatives(self.generator).astype(float) + self.shift
        adjugate = integer_adjugate3(self.generator).astype(float)
        points = offsets @ adjugate.T / float(self.determinant)
        points = wrap_fractional(points)
        order = np.lexsort((points[:, 2], points[:, 1], points[:, 0]))
        return np.ascontiguousarray(points[order])

    def contains(self, kpoints: ArrayLike, *, atol: float = 1e-6) -> NDArray[np.bool_]:
        """Which of ``kpoints`` (fractional, shape ``(n, 3)``) are mesh points."""

        tol = check_atol(atol)
        points = np.atleast_2d(np.asarray(kpoints, dtype=float))
        if points.ndim != 2 or points.shape[1] != 3:
            raise ValueError("kpoints must have shape (n_kpoints, 3)")
        residual = points @ self.generator.astype(float).T - self.shift
        residual -= np.rint(residual)
        return np.all(np.abs(residual) <= tol, axis=1)

    def axis_divisions(self) -> tuple[int, int, int]:
        """Number of distinct values each fractional component takes.

        The i-th coordinates of the mesh points form the group generated by
        ``gcd_j adj(M)[i, j] / det M``, so the count along axis ``i`` is
        ``|det M| / gcd_j adj(M)[i, j]``.  The product of the three exceeds
        ``|det M|`` exactly when the mesh is not a product of one-dimensional
        meshes.
        """

        adjugate = integer_adjugate3(self.generator)
        counts: list[int] = []
        for row in adjugate:
            divisor = 0
            for value in row:
                divisor = gcd(divisor, abs(int(value)))
            counts.append(self.count if divisor == 0 else self.count // gcd(divisor, self.count))
        return counts[0], counts[1], counts[2]

    @property
    def is_product_mesh(self) -> bool:
        """Whether the mesh is a product of one-dimensional meshes.

        A Monkhorst--Pack specification -- three divisions and a shift --
        describes a product mesh and nothing else.  An unfolded mesh generally
        fails this (``UnfoldLab.exists_unfoldedMesh_not_product``).
        """

        n1, n2, n3 = self.axis_divisions()
        return n1 * n2 * n3 == self.count

    def to_dict(self) -> dict[str, Any]:
        return {
            "generator": self.generator.tolist(),
            "shift": self.shift.tolist(),
            "count": self.count,
            "gamma_centred": self.is_gamma_centred,
            "axis_divisions": list(self.axis_divisions()),
            "product_mesh": self.is_product_mesh,
        }


def unfolded_mesh(mesh: MeshSpec, transform: TransformLike | TransformationMatrix) -> MeshSpec:
    """The mesh of primitive k-points a supercell mesh resolves.

    ``UnfoldLab.unfoldedMesh_eq``: it is generated by ``M @ T`` with the same
    shift, and therefore has ``|det M| * |det T|`` points.
    """

    matrix = _transform_matrix(transform)
    return MeshSpec(generator=mesh.generator @ matrix, shift=mesh.shift)


def unfolded_mesh_points(
    mesh: MeshSpec, transform: TransformLike | TransformationMatrix
) -> NDArray[np.float64]:
    """The resolvable primitive k-points, as a ``(|det M| |det T|, 3)`` array."""

    return unfolded_mesh(mesh, transform).points()


def mesh_kpoint_mappings(
    mesh: MeshSpec, transform: TransformLike | TransformationMatrix
) -> list[KPointMapping]:
    """Every resolvable primitive k-point paired with the supercell k-point it needs.

    This is the mesh counterpart of
    :func:`unfoldlab.core.kpoints.fiber_kpoint_mappings`: feeding the result to
    an unfolding run covers each fiber completely
    (``UnfoldLab.IsFiberRepr.mesh_fiber_complete``), so the sum-rule diagnostics
    verify the calculation instead of merely bounding it.  The weights are
    uniform and add to one, which is what a Brillouin-zone integral over a
    regular mesh needs.
    """

    matrix = TransformationMatrix.from_values(_transform_matrix(transform))
    points = unfolded_mesh_points(mesh, matrix)
    share = 1.0 / float(points.shape[0])
    mappings: list[KPointMapping] = []
    for point in points:
        primitive = KPoint(point, weight=share)
        supercell = fold_kpoint_to_supercell(primitive, matrix)
        mappings.append(KPointMapping(primitive=primitive, supercell=supercell))
    return mappings


def _mesh_lattice(mesh: MeshSpec, reciprocal_lattice: ArrayLike) -> NDArray[np.float64]:
    """Cartesian rows of the mesh translations, ``(M^-1)^T B``."""

    lattice = as_matrix3(reciprocal_lattice, name="reciprocal_lattice")
    adjugate = integer_adjugate3(mesh.generator).astype(float)
    return adjugate.T / float(mesh.determinant) @ lattice


def mesh_distance(
    mesh: MeshSpec, kpoint: ArrayLike, reciprocal_lattice: ArrayLike | None = None
) -> float:
    """Distance from ``kpoint`` to the nearest point of ``mesh``.

    With ``reciprocal_lattice`` (rows = Cartesian reciprocal lattice vectors)
    the distance is Cartesian and the minimization over mesh translations is the
    certified search of :func:`unfoldlab.core.valleys.minimum_image_distance`;
    without it, the Euclidean norm of the fractional offset in mesh-index units
    divided by the mesh spacing is returned, which is only meaningful for a
    cubic cell.

    This is the error made by substituting the nearest available k-point for a
    requested one, and ``UnfoldLab.mesh_resolution_bound`` says it can reach
    half a mesh spacing.
    """

    k = as_array3(kpoint, name="kpoint")
    residual = mesh.generator.astype(float) @ k - mesh.shift
    if reciprocal_lattice is None:
        adjugate = integer_adjugate3(mesh.generator).astype(float)
        offset = residual - np.rint(residual)
        return float(np.linalg.norm(adjugate @ offset / float(mesh.determinant)))
    return minimum_image_distance(residual, _mesh_lattice(mesh, reciprocal_lattice))


def nearest_mesh_point(
    mesh: MeshSpec,
    kpoint: ArrayLike,
    reciprocal_lattice: ArrayLike | None = None,
    *,
    max_radius: int = 4,
) -> NDArray[np.float64]:
    """A mesh point at the distance reported by :func:`mesh_distance`.

    Without ``reciprocal_lattice`` the index vector is rounded componentwise,
    which is the nearest point in the mesh-index metric.  With one, candidates
    around the rounded index are searched outwards until one attains the
    certified minimum distance, because componentwise rounding is *not* the
    nearest point of a non-orthogonal lattice
    (``UnfoldLab.exists_shorter_image_than_reduced``).
    """

    k = as_array3(kpoint, name="kpoint")
    adjugate = integer_adjugate3(mesh.generator).astype(float)
    residual = mesh.generator.astype(float) @ k - mesh.shift
    base = np.rint(residual)

    def point_of(index: NDArray[np.float64]) -> NDArray[np.float64]:
        return adjugate @ (index + mesh.shift) / float(mesh.determinant)

    if reciprocal_lattice is None:
        return point_of(base)

    lattice = _mesh_lattice(mesh, reciprocal_lattice)
    target = minimum_image_distance(residual, lattice)
    best = base
    best_distance = float("inf")
    for radius in range(1, max_radius + 1):
        for delta in product(range(-radius, radius + 1), repeat=3):
            if max(abs(value) for value in delta) != radius and radius > 1:
                continue
            index = base + np.asarray(delta, dtype=float)
            distance = float(np.linalg.norm((residual - index) @ lattice))
            if distance < best_distance:
                best_distance = distance
                best = index
        if best_distance <= target + 1e-9:
            break
    return point_of(best)


@dataclass(frozen=True)
class MeshReport:
    """What a supercell mesh can and cannot resolve."""

    supercell_mesh: MeshSpec
    primitive_mesh: MeshSpec
    multiplicity: int
    gamma_resolved: bool
    zone_boundary_resolved: tuple[bool, bool, bool]
    axis_divisions: tuple[int, int, int]
    is_product_mesh: bool
    requested: NDArray[np.float64]
    resolved: NDArray[np.bool_]
    distances: NDArray[np.float64]
    cartesian: bool

    @property
    def max_distance(self) -> float:
        """Largest distance from a requested k-point to a resolvable one."""

        return float(self.distances.max()) if self.distances.size else 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "supercell_mesh": self.supercell_mesh.to_dict(),
            "primitive_mesh": self.primitive_mesh.to_dict(),
            "multiplicity": self.multiplicity,
            "n_supercell_kpoints": self.supercell_mesh.count,
            "n_primitive_kpoints": self.primitive_mesh.count,
            "gamma_resolved": self.gamma_resolved,
            "zone_boundary_resolved": list(self.zone_boundary_resolved),
            "axis_divisions": list(self.axis_divisions),
            "product_mesh": self.is_product_mesh,
            "requested": self.requested.tolist(),
            "resolved": self.resolved.tolist(),
            "distances": self.distances.tolist(),
            "max_distance": self.max_distance,
            "cartesian_distances": self.cartesian,
        }


def diagnose_mesh(
    mesh: MeshSpec,
    transform: TransformLike | TransformationMatrix,
    *,
    requested: ArrayLike | None = None,
    reciprocal_lattice: ArrayLike | None = None,
    atol: float = 1e-6,
) -> MeshReport:
    """Report which primitive k-points a supercell mesh resolves.

    ``requested`` is an optional list of fractional primitive k-points -- the
    high-symmetry points or the band path one would like to plot.  Each is
    tested for membership of the unfolded mesh, and the distance to the nearest
    resolvable point is reported: Cartesian when ``reciprocal_lattice`` is
    given, in fractional units otherwise.
    """

    matrix = _transform_matrix(transform)
    primitive = unfolded_mesh(mesh, matrix)
    multiplicity = abs(integer_det3(matrix))
    if requested is None:
        points = np.zeros((0, 3), dtype=float)
    else:
        points = np.atleast_2d(np.asarray(requested, dtype=float))
        if points.ndim != 2 or points.shape[1] != 3:
            raise ValueError("requested must have shape (n_kpoints, 3)")
    resolved = primitive.contains(points, atol=atol) if points.size else np.zeros(0, dtype=bool)
    distances = np.array(
        [mesh_distance(primitive, point, reciprocal_lattice) for point in points], dtype=float
    )
    boundary = tuple(
        bool(primitive.contains(np.eye(3)[axis] / 2.0, atol=atol)[0]) for axis in (0, 1, 2)
    )
    return MeshReport(
        supercell_mesh=mesh,
        primitive_mesh=primitive,
        multiplicity=multiplicity,
        gamma_resolved=bool(primitive.contains(np.zeros(3), atol=atol)[0]),
        zone_boundary_resolved=(boundary[0], boundary[1], boundary[2]),
        axis_divisions=primitive.axis_divisions(),
        is_product_mesh=primitive.is_product_mesh,
        requested=points,
        resolved=np.asarray(resolved, dtype=bool),
        distances=distances,
        cartesian=reciprocal_lattice is not None,
    )
